function dateHelper(days) {
  let date = new Date();
  date.setDate(date.getDate() + days);
  const options = { day: '2-digit', month: 'long', year: 'numeric' };
  return date.toLocaleDateString('en-US', options);
}
  export const countries = [
    // {
    //   id: Math.random(),
    //   name: "ALbania",
    //   pic: "/images/albania.jpg",
    //   price: "     10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Angola",
      pic:  "/images/angola.jpg",
      price: "7000",
      date: dateHelper(7),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 7,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Antigua and Burbuda",
      pic: "/images/antigua-burbuda.jpg",
      price: "10800",
      date: dateHelper(8),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 8,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Argentina",
      pic: "/images/argentina.jpg",
      price: "19000",
      date: dateHelper(31),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 31,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Armenia",
      pic: "/images/armenia.jpg",
      price: "1600",
      date: dateHelper(7),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 7,
      docs: ["Photo", "Passport", "Hotel Bookings", "Bank Statement"],
    },
    {
      id: Math.random(),
      name: "Australia",
      pic: "/images/australia.jpg",
      price: "4500",
      date: dateHelper(27),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 27,
      docs: [
        "Passport",
        "Photo",
        "Bank Statement",
        "ITR",
        "Employement Documents",
      ],
    },
    {
      id: Math.random(),
      name: "Austria",
      pic: "./images/austria.jpg",
      price: "4500",
      date: dateHelper(21),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 21,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Azerbaijan",
      pic: "/images/azerbaijan.jpg",
      price: "10000",
      date: dateHelper(1),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 1,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Bahrain",
      pic: "/images/bahrain.jpg",
      price: "3900",
      date: dateHelper(5),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 5,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Bangladesh",
      pic: "/images/bangladesh.jpg",
      price: "3900",
      date: dateHelper(15),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 15,
      docs: ["Photo", "Passport"],
    },
    // {
    //   id: Math.random(),
    //   name: "Barbados",
    //   pic: "/images/barbados.jpg",
    //   price: "     10000",
    //   date: new Date()
    // },
    // {
    //   id: Math.random(),
    //   name: "Belarus",
    //   pic: "/images/belarus.jpg",
    //   price: "     10000",
    //   date: new Date()
    // },
    {
      id: Math.random(),
      name: "Belgium",
      pic: "/images/belgium.jpg",
      price: "4500",
      date: dateHelper(27),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 27,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Benin",
      pic: "/images/benin.jpg",
      price: "6800",
      date: dateHelper(9),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 9,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Bhutan",
      pic: "/images/bhutan.jpg",
      price: "11200",
      date: dateHelper(8),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 8,
      docs: ["Photo", "Passport", "Hotel Bookings"],
    },
    {
      id: Math.random(),
      name: "Brazil",
      pic: "/images/brazil.jpg",
      price: "10800",
      date: dateHelper(17),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 17,
      docs: ["Photo", "Passport", "Bank Statement", "Flight Bookings"],
    },
    {
      id: Math.random(),
      name: "Burkina Faso",
      pic: "/images/burkina-faso.jpg",
      price: "8400",
      date: dateHelper(8),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 8,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Cambodia",
      pic: "/images/cambodia.jpg",
      price: "3900",
      date: dateHelper(6),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 6,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Canada",
      pic: "/images/canada.jpg",
      price: "25000",
      date: dateHelper(46),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 46,
      docs: ["Photo", "Passport", "Bank Statement", "Flight Bookings", "ITR"],
    },
    {
      id: Math.random(),
      name: "Chile",
      pic: "/images/chile.jpg",
      price: "15300",
      date: dateHelper(29),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 29,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "China",
      pic: "/images/china.jpg",
      price: "7500",
      date: dateHelper(9),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 9,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Colombia",
      pic: "/images/colombia.jpg",
      price: "14800",
      date: dateHelper(29),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 29,
      docs: ["Photo", "Passport"],
    },
    // {
    //   id: Math.random(),
    //   name: "Comoros",
    //   pic: "/images/comoros.jpg",
    //   price: "     10000",
    //   date:new Date()
    // },
    // {
    //   id: Math.random(),
    //   name: "Cook Island",
    //   pic: "/images/cook-island.jpg",
    //   price: "     10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Costa Rica",
      pic: "/images/costa-rica.jpg",
      price: "4800",
      date: dateHelper(24),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 24,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Cuba",
      pic: "/images/cuba.jpg",
      price: "9500",
      date: dateHelper(23),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 23,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Cyprus",
      pic: "/images/cyprus.jpg",
      price: "4500",
      date: dateHelper(11),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 11,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Czechia",
      pic: "/images/czechia.jpg",
      price: "4500",
      date: dateHelper(21),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 21,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Eqypt",
      pic: "/images/egypt.jpg",
      price: "4200",
      date: dateHelper(4),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 4,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Ethiopia",
      pic: "/images/ehtiopia.jpg",
      price: "8300",
      date: dateHelper(7),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 7,
      docs: ["Photo", "Passport"],
    },
    // {
    //   id: Math.random(),
    //   name: "El Salvador",
    //   pic: "/images/el-salvador.jpg",
    //   price: "     10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Equitorial Guinea",
      pic: "/images/equitorial-guinea.jpg",
      price: "11500",
      date: dateHelper(8),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 8,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Estonia",
      pic: "/images/estonia.jpg",
      price: "4500",
      date: dateHelper(27),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 27,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Fiji",
      pic: "/images/fiji.jpg",
      tag: "Get Visa response on time or 100% return",
      price: "     10000",
      date: dateHelper(27),
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 27,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Finland",
      pic: "/images/finland.jpg",
      price: "4500",
      date: dateHelper(27),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 27,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "France",
      pic: "/images/france.jpg",
      price: "4500",
      date: dateHelper(27),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 27,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Georgia",
      pic: "/images/georgia.jpg",
      price: "8000",
      date: dateHelper(12),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 12,
      docs: [
        "Photo",
        "Passport",
        "Bank Statement",
        "Flight Bookings",
        "Hotel Bookings",
      ],
    },
    {
      id: Math.random(),
      name: "Germany",
      pic: "/images/germany.jpg",
      price: "4500",
      date: dateHelper(28),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 28,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Ghana",
      pic: "/images/ghana.jpg",
      price: "12500",
      date: dateHelper(24),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 24,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Greece",
      pic: "/images/greece.jpg",
      price: "4500",
      date: dateHelper(31),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 31,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Guinea",
      pic: "/images/guinea.jpg",
      price: "8900",
      date: dateHelper(10),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 10,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Guyana",
      pic: "/images/guyana.jpg",
      price: "1100",
      date: dateHelper(30),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 30,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Hong Kong",
      pic: "/images/hong-kong.jpg",
      price: "1700",
      date: dateHelper(1),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 1,
      docs: ["Passport"],
    },
    {
      id: Math.random(),
      name: "Hungary",
      pic: "/images/hungary.jpg",
      price: "4500",
      date: dateHelper(26),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 26,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Indonesia",
      pic: "/images/indonesia.jpg",
      price: "6000",
      date: dateHelper(3),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 3,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Israel",
      pic: "/images/israel.jpg",
      price: "12800",
      date: dateHelper(32),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 32,
      docs: [
        "Photo",
        "Passport",
        "Bank Statement",
        "Flight Bookings",
        "Hotel Bookings",
        "ITR",
      ],
    },
    {
      id: Math.random(),
      name: "Italy",
      pic: "/images/italy.jpg",
      price: "4500",
      date: dateHelper(33),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 33,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Japan",
      pic: "/images/japan.jpg",
      price: "3000",
      date: dateHelper(25),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 25,
      docs: [
        "Photo",
        "Passport",
        "Bank Statements",
        "Flight Bookings",
        "Hotel Bookings",
        "ITR",
      ],
    },
    {
      id: Math.random(),
      name: "Jordan",
      pic: "/images/jordan.jpg",
      price: "6200",
      date: dateHelper(2),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 2,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Kenya",
      pic: "/images/kenya.jpg",
      price: "4800",
      date: dateHelper(6),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 6,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Kyrgyzstan",
      pic: "/images/kyrgyzstan.jpg",
      price: "17300",
      date: dateHelper(16),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 16,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Laos",
      pic: "/images/laos.jpg",
      price: "4500",
      date: dateHelper(8),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 8,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Lebanon",
      pic: "/images/lebanon.jpg",
      price: "10700",
      date: dateHelper(30),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 30,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Liechtenstein",
      pic: "/images/liechtenstein.jpg",
      price: "4500",
      date: dateHelper(21),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 21,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Madagascar",
      pic: "/images/madagascar.jpg",
      price: "2800",
      date: dateHelper(3),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 3,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Malaysia",
      pic: "/images/malaysia.png",
      price: "2500",
      date: dateHelper(3),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 3,
      docs: ["Photo", "Passport", "Flight Bookings", "Hotel Bookings"],
    },
    // {
    //   id: Math.random(),
    //   name: "Maldives",
    //   pic: "./images/maldives.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Malta",
      pic: "/images/malta.jpg",
      price: "4500",
      date: dateHelper(26),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 26,
      docs: ["Photo", "Passport"],
    },
    // {
    //   id: Math.random(),
    //   name: "Marshall Island",
    //   pic: "./images/marshall-island.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    // {
    //   id: Math.random(),
    //   name: "Mauritius",
    //   pic: "./images/mauritius.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    // {
    //   id: Math.random(),
    //   name: "Moldova",
    //   pic: "./images/moldova.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Mongolia",
      pic: "/images/mongolia.jpg",
      price: "1450",
      date: dateHelper(4),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 4,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Morocco",
      pic: "/images/morocco.jpg",
      price: "7800",
      date: dateHelper(6),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 6,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Mozambique",
      pic: "/images/mozambique.jpg",
      price: "14500",
      date: dateHelper(10),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 10,
      docs: ["Photo", "Passport"],
    },
    // {
    //   id: Math.random(),
    //   name: "Nepal",
    //   pic: "/images/nepal.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Netherlands",
      pic: "/images/netherlands.jpg",
      price: "4500",
      date: dateHelper(27),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 27,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "New Zealand",
      pic: "/images/new-zealand.jpg",
      price: "16500",
      date: dateHelper(31),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 31,
      docs: ["Photo", "Passport", "Bank Statement", "ITR", "Hotel Bookings"],
    },
    {
      id: Math.random(),
      name: "Norway",
      pic: "/images/norway.jpg",
      price: "4500",
      date: dateHelper(26),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 26,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Oman",
      pic: "/images/oman.jpg",
      price: "8000",
      date: dateHelper(7),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 7,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Papua Guinea",
      pic: "/images/papua-guinea.jpg",
      price: "6500",
      date: dateHelper(10),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 10,
      docs: ["Photo", "Passport"],
    },
    // {
    //   id: Math.random(),
    //   name: "Oleksandr P",
    //   pic: "/images/pexels-oleksandr-p-1002541.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Philippines",
      pic: "/images/philippines.jpg",
      price: "6000",
      date: dateHelper(29),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 29,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Poland",
      pic: "/images/poland.jpg",
      price: "4500",
      date: dateHelper(21),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 21,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Qatar",
      pic: "/images/qatar.jpg",
      price: "2400",
      date: dateHelper(7),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 7,
      docs: ["Photo", "Passport", "Hotel Bookings from Discover Qatar"],
    },
    {
      id: Math.random(),
      name: "Russia",
      pic: "/images/russia.jpg",
      price: "5600",
      date: dateHelper(9),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 9,
      docs: ["Photo", "Passport", "Hotel bookings", "Flight Details"],
    },
    {
      id: Math.random(),
      name: "Rwanda",
      pic: "/images/rwanda.jpg",
      price: "5300",
      date: dateHelper(8),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 8,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Saudi Arabia",
      pic: "/images/saudi-arabia.jpg",
      price: "11800",
      date: dateHelper(5),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 5,
      docs: [
        "Photo",
        "Passport",
        "Hotel Bookings",
        "Bank Statement",
        "Employement Documents",
      ],
    },
    // {
    //   id: Math.random(),
    //   name: "Senegal",
    //   pic: "./images/senegal.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    // {
    //   id: Math.random(),
    //   name: "Seychelles",
    //   pic: "/images/seychelles.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Singapore",
      pic: "/images/singapore.jpg",
      price: "3000",
      date: dateHelper(10),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 10,
      docs: [
        "Hotel Bookings",
        "Photo",
        "Passport",
        "Employement Details",
        "Bank Statement",
      ],
    },
    {
      id: Math.random(),
      name: "Slovakia",
      pic: "/images/slovakia.jpg",
      price: "4500",
      date: dateHelper(21),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 21,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Slovenia",
      pic: "/images/slovenia.jpg",
      price: "4500",
      date: dateHelper(23),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 23,
      docs: ["Photo", "Passport"],
    },
    // {
    //   id: Math.random(),
    //   name: "Somalia",
    //   pic: "./images/somalia.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "South Africa",
      pic: "/images/south-africa.jpg",
      price: "7100",
      date: dateHelper(31),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 31,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "South Korea",
      pic: "/images/south-korea.jpg",
      price: "7100",
      date: dateHelper(29),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 29,
      docs: [
        "Photo",
        "Passport",
        "Bank Statement",
        "Flight Bookings",
        "Hotel Bookings",
      ],
    },
    {
      id: Math.random(),
      name: "Spain",
      pic: "/images/spain.jpg",
      price: "5500",
      date: dateHelper(27),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 27,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Sri Lanka",
      pic: "/images/srilanka.jpeg",
      price: "2900",
      date: dateHelper(2),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 2,
      docs: ["Photo", "Passport"],
    },
    // {
    //   id: Math.random(),
    //   name: "Saint Kitts and Nevis",
    //   pic: "./images/st-kitts-nevis.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    // {
    //   id: Math.random(),
    //   name: "Saint Lucia",
    //   pic: "./images/st-lucia.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Sweden",
      pic: "/images/sweden.jpg",
      price: "4500",
      date: dateHelper(26),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 26,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Switzerland",
      pic: "/images/switzerland.jpg",
      price: "4500",
      date: dateHelper(26),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 26,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Taiwan",
      pic: "/images/taiwan.jpg",
      price: "2800",
      date: dateHelper(3),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 3,
      docs: ["Photo", "Passport", "Flight Bookings"],
    },
    {
      id: Math.random(),
      name: "Tajikistan",
      pic: "/images/tajikistan.jpg",
      price: "6800",
      date: dateHelper(14),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 14,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Tanzania",
      pic: "/images/tanzania.jpg",
      price: "5600",
      date: dateHelper(14),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 14,
      docs: ["Photo", "Passport"],
    },
    // {
    //   id: Math.random(),
    //   name: "Thailand",
    //   pic: "./images/thailand.jpg",
    //   price: "10000",
    //   date:new Date()
    // },
    {
      id: Math.random(),
      name: "Turkiye",
      pic: "/images/turkiye.jpg",
      price: "9300",
      date: dateHelper(20),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 20,
      docs: ["Photo", "Passport", "Bank Statement", "Employement Documents"],
    },
    {
      id: Math.random(),
      name: "UAE",
      pic: "/images/UAE.jpg",
      price: "8400",
      date: dateHelper(3),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 3,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "United Kingdom",
      pic: "/images/uk.jpg",
      price: "19000",
      date: dateHelper(40),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 40,
      docs: [
        "Photo",
        "Passport",
        "Hotel Bookings",
        "Bank Statement",
        "Employement Documents",
      ],
    },
    {
      id: Math.random(),
      name: "Uruguay",
      pic: "/images/uruguay.jpg",
      price: "5200",
      date: dateHelper(24),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 24,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "United States",
      pic: "/images/us.jpg",
      price: "31500",
      date: dateHelper(94),
      tag: "Get Visa response on time or 100% return",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 94,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Uzbekistan",
      pic: "/images/uzbekistan.jpg",
      price: "2700",
      date: dateHelper(7),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 7,
      docs: ["Photo", "Passport"],
    },
    {
      id: Math.random(),
      name: "Vietnam",
      pic: "/images/vietnam.jpg",
      price: "2850",
      date: dateHelper(7),
      tag: "Get Visa response on time or free",
      notice: "Public Holidays and weekends are considered as non working days.",
      days: 7,
      docs: ["Photo", "Passport"],
    },
  ];